In [0]:
import numpy as np
import pandas as pd


In [0]:
jo = open("wheelership.txt", encoding='utf-8').read()

In [3]:
print(jo)

New 17 x 7" Wheel for Chevrolet Equinox 2010 2011 2012 2013 2014 2015 2016 Rim 5433"
New 17 x 7.5" Front Replacement Wheel for Mercedes C230 C350 2007 Rim 65436"
OE Genuine Tesla Center Cap W/ Tesla Logo Silver
New 17 x 7" Replacement Wheel for Honda Civic 2006 2007 2008 Rim 63901"
New 17 x 7" Replacement Wheel for Ford Focus 2015 2016 2017 2018 Rim 10012"
0
ALY70727U20N
Brand New 18 x 8.5" Replacement Wheel for Mercedes CLS500 CLS550 2006-2007 Rim 65371"
New 16 Alloy Replacement Wheel for Volkswagen Jetta 2010 2011 2012 2013 2014 2015 Rim 69897"
New Mirror Glass Replacements For Chevy C4500 Kodiak, GMC Topkick 2003-2009 Upper Flat
New 16 Alloy Replacement Wheel for Volkswagen Jetta 2010 2011 2012 2013 2014 2015 Rim 69897"
New 17 x 8" Replacement Wheel for Lexus IS250 IS350 2006 2007 2008 Rim 74188"
New 19 x 9"  Alloy Rear Wheel for Chrysler Crossfire 2004 2005 2006 2007 2008 Rim 2230"
New 17 x 8" Alloy Replacement Wheel for Acura TL 2007-2008 Rim 71762"
New 22 Wheel for Cadillac Escal

In [0]:
##split the data into words
corpus = jo.split()

In [5]:
print(corpus)

['New', '17', 'x', '7"', 'Wheel', 'for', 'Chevrolet', 'Equinox', '2010', '2011', '2012', '2013', '2014', '2015', '2016', 'Rim', '5433"', 'New', '17', 'x', '7.5"', 'Front', 'Replacement', 'Wheel', 'for', 'Mercedes', 'C230', 'C350', '2007', 'Rim', '65436"', 'OE', 'Genuine', 'Tesla', 'Center', 'Cap', 'W/', 'Tesla', 'Logo', 'Silver', 'New', '17', 'x', '7"', 'Replacement', 'Wheel', 'for', 'Honda', 'Civic', '2006', '2007', '2008', 'Rim', '63901"', 'New', '17', 'x', '7"', 'Replacement', 'Wheel', 'for', 'Ford', 'Focus', '2015', '2016', '2017', '2018', 'Rim', '10012"', '0', 'ALY70727U20N', 'Brand', 'New', '18', 'x', '8.5"', 'Replacement', 'Wheel', 'for', 'Mercedes', 'CLS500', 'CLS550', '2006-2007', 'Rim', '65371"', 'New', '16', 'Alloy', 'Replacement', 'Wheel', 'for', 'Volkswagen', 'Jetta', '2010', '2011', '2012', '2013', '2014', '2015', 'Rim', '69897"', 'New', 'Mirror', 'Glass', 'Replacements', 'For', 'Chevy', 'C4500', 'Kodiak,', 'GMC', 'Topkick', '2003-2009', 'Upper', 'Flat', 'New', '16', 'All

In [0]:
def make_pairs(corpus):
    for i in range(len(corpus) - 1):
        yield(corpus[i], corpus[i+1])

pairs = make_pairs(corpus)


In [0]:
##appending the dictionary

word_dict = {}

for word_1, word_2 in pairs:
    if word_1 in word_dict.keys():
        word_dict[word_1].append(word_2)
    else:
        word_dict[word_1] = [word_2]

In [0]:
##building the markov model

first_word = np.random.choice(corpus)

while first_word.islower():
    first_word = np.random.choice(corpus)

chain = [first_word]

n_words = 20

for i in range(n_words):
    chain.append(np.random.choice(word_dict[chain[-1]]))

In [65]:
##prediction

xy = (' '.join(chain))
print(xy)

E-Series E-150 E-250 SD E-350 F-Series Excursion 1999-2015 Driver Left Side New 18 x 8.5" Front Wheel for Pontiac G6 2005


In [10]:
!pip install seaborn

In [0]:
##detection
##ML Packages For Vectorization of Text For Feature Extraction
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

# Visualization Packages
import matplotlib.pyplot as plt
import seaborn as sns

In [15]:
df = pd.read_csv("SalesData1.csv", error_bad_lines = False)

b'Skipping line 7: expected 52 fields, saw 54\nSkipping line 8: expected 52 fields, saw 53\nSkipping line 28: expected 52 fields, saw 54\nSkipping line 62: expected 52 fields, saw 54\nSkipping line 64: expected 52 fields, saw 54\nSkipping line 69: expected 52 fields, saw 53\nSkipping line 76: expected 52 fields, saw 54\nSkipping line 81: expected 52 fields, saw 53\nSkipping line 86: expected 52 fields, saw 54\nSkipping line 112: expected 52 fields, saw 54\nSkipping line 125: expected 52 fields, saw 54\nSkipping line 127: expected 52 fields, saw 54\nSkipping line 131: expected 52 fields, saw 54\nSkipping line 136: expected 52 fields, saw 53\nSkipping line 151: expected 52 fields, saw 54\nSkipping line 163: expected 52 fields, saw 53\nSkipping line 168: expected 52 fields, saw 54\nSkipping line 200: expected 52 fields, saw 54\nSkipping line 203: expected 52 fields, saw 54\nSkipping line 220: expected 52 fields, saw 54\nSkipping line 261: expected 52 fields, saw 54\nSkipping line 278: exp

In [0]:
a = df['weight'].mean

In [17]:
a

<bound method Series.mean of 0       28.4000
1       28.3000
2        0.1675
3       27.3000
4       27.0000
         ...   
7676    28.8000
7677    26.2000
7678     0.6000
7679    32.3000
7680    30.6000
Name: weight, Length: 7681, dtype: float64>

In [18]:
df['weight'].fillna(a)

0       28.4000
1       28.3000
2        0.1675
3       27.3000
4       27.0000
         ...   
7676    28.8000
7677    26.2000
7678     0.6000
7679    32.3000
7680    30.6000
Name: weight, Length: 7681, dtype: float64

In [27]:
types = {'simple': 1,'bundle': 2, 'other':3}
df.product_type = [types[item] for item in df.product_type] 



KeyError: ignored

In [28]:
df.head()

id  item_id  ...            createdAt            updatedAt
0   1   118641  ...  2019-08-12 15:28:36  2019-08-12 15:28:36
1   2   118640  ...  2019-08-12 15:28:38  2019-08-12 15:28:38
2   3   118642  ...  2019-08-12 15:28:40  2019-08-12 15:28:40
3   4   118643  ...  2019-08-12 15:28:42  2019-08-12 15:28:42
4   5   118644  ...  2019-08-12 15:28:44  2019-08-12 15:28:44

[5 rows x 52 columns]

In [43]:
df.tail()

id  item_id  ...            createdAt            updatedAt
7676  9993   114567  ...  2019-08-14 01:15:18  2019-08-14 01:15:18
7677  9995   114569  ...  2019-08-14 01:15:22  2019-08-14 01:15:22
7678  9996   114570  ...  2019-08-14 01:15:24  2019-08-14 01:15:24
7679  9998   114572  ...  2019-08-14 01:15:28  2019-08-14 01:15:28
7680  9999   114573  ...  2019-08-14 01:15:30  2019-08-14 01:15:30

[5 rows x 52 columns]

In [0]:
df_x = df['name']
df_y = df['product_type']

In [0]:
cv = CountVectorizer()
ex = cv.fit_transform(["Replacement for Honda Civic"])

In [31]:
ex.toarray()


array([[1, 1, 1, 1]])

In [32]:
cv.get_feature_names()


['civic', 'for', 'honda', 'replacement']

In [0]:
# Extract Feature With CountVectorizer
corpus = df_x
cv = CountVectorizer()
X = cv.fit_transform(corpus) # Fit the Data

In [34]:
X.toarray()


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [35]:
# get the feature names
cv.get_feature_names()

['00',
 '001b',
 '003a',
 '004a',
 '02',
 '08',
 '0r020',
 '10010',
 '10012',
 '10031',
 '15',
 '150',
 '1500',
 '16',
 '17',
 '18',
 '19',
 '1993',
 '1994',
 '1996',
 '1997',
 '1999',
 '20',
 '200',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '21',
 '22',
 '2201',
 '2229',
 '2230',
 '2481',
 '2498',
 '250',
 '2500',
 '2515',
 '2517',
 '2734',
 '2752',
 '2763',
 '2829',
 '2844',
 '2955',
 '2980',
 '300',
 '323i',
 '325i',
 '328i',
 '330',
 '330i',
 '3310',
 '335i',
 '3466',
 '350',
 '3500',
 '3628',
 '3629',
 '3632',
 '3646',
 '3648',
 '3656',
 '3678',
 '3702',
 '3705',
 '3760',
 '3768',
 '3787',
 '3797',
 '3817',
 '3886',
 '3895',
 '3904',
 '3924',
 '3926',
 '3947',
 '3959',
 '3961',
 '400',
 '4018',
 '4063',
 '4095',
 '4106',
 '4114',
 '4119',
 '4127',
 '4260b',
 '430',
 '44733tbaa12',
 '4578',
 '4739',
 '4741',
 '500',
 '5001a',
 '5071',
 '5116',
 

In [0]:
from sklearn.model_selection import train_test_split


In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, df_y, test_size=0.33, random_state=42)


In [38]:
X_train


<5146x643 sparse matrix of type '<class 'numpy.int64'>'
	with 72589 stored elements in Compressed Sparse Row format>

In [39]:
# Naive Bayes Classifier
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

0.9913214990138067

In [40]:

# Accuracy of our Model
print("Accuracy of Model",clf.score(X_test,y_test)*100,"%")

Accuracy of Model 99.13214990138067 %


In [41]:
## Predicting with our model
clf.predict(X_test)

array([1, 1, 1, ..., 1, 1, 1])

In [0]:
# Sample Prediciton
comment = ["Set of 4 New 16 x 7 Wheel for Honda Accord LX 2016 2017 Rim 64078 with Center Caps"]
vect = cv.transform(comment).toarray()

In [45]:
clf.predict(vect)


array([2])

In [0]:
class_dict = {'simple':0,'bundle':1}


In [47]:
class_dict.values()


dict_values([0, 1])

In [49]:
if clf.predict(vect) == 1:
    print("bundle")
else:
    print("simple")

simple


In [50]:
# Sample Prediciton 2
comment1 = ["Great song Friend"]
vect = cv.transform(comment1).toarray()
clf.predict(vect)

array([1])

In [51]:
!pip install pickle

ERROR: Could not find a version that satisfies the requirement pickle (from versions: none)
ERROR: No matching distribution found for pickle


In [0]:
import pickle


In [0]:
naivebayesML = open("twllc.pkl","wb")


In [0]:
pickle.dump(clf,naivebayesML)


In [0]:
naivebayesML.close()


In [0]:
ytb_model = open("twllc.pkl","rb")


In [0]:
new_model = pickle.load(ytb_model)


In [58]:
new_model

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [68]:
# Sample Prediciton 3
comment2 = ['E-Series E-150 E-250 SD E-350 F-Series Excursion 1999-2015 Driver Left Side New 18 x 8.5" Front Wheel for Pontiac G6 2005']
vect = cv.transform(comment2).toarray()
new_model.predict(vect)

array([1])

In [69]:
if new_model.predict(vect) == 1:
    print("Bundle")
else:
    print("Simple")

Bundle
